### ISSUE TITLE
How to use this program? Can it be compiled into an EXE program?

### ISSUE THREAD

**Issue by wlzjd** [newagesoftwareLLC/DWG-to-PDF-Watcher#2]
How to use this program? Can it be compiled into an EXE program?

**Comment by erfg12** [comment]
Currently the software is going through framework changes at the moment.

**Comment by erfg12** [comment]
Here's the latest compiled version: https://github.com/newagesoftwareLLC/DWG-to-PDF-Watcher/releases/tag/1.4
